repos:
  - repo: local
    hooks:
      - id: notebook-diff
        name: Generate notebook diff with nbdime
        entry: ./scripts/generate_notebook_diff.sh
        language: script
        files: \.ipynb$
        pass_filenames: false
